services:
  arangodb:
    image: arangodb:3.10
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_PASSWORD}
#     volumes:
#       - arango-volume:/var/lib/arangodb3
    ports:
    - 8529:8529

volumes:
  arango-volume:
    driver: local